package msgbus

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/nats-io/nats.go"

	"github.com/TrueOpen/nexus/internal/config"
)

// ADR-0016 transition state: the client connects to NATS over tls:// with a creds file (JWT + seed) instead
// of a username and password. This only checks how the connection options are assembled and starts no real NATS.

func applyOptions(t *testing.T, cfg config.NATSConfig) nats.Options {
	t.Helper()
	opts, err := natsConnectOptions(cfg)
	if err != nil {
		t.Fatalf("natsConnectOptions: %v", err)
	}
	applied := nats.GetDefaultOptions()
	for _, opt := range opts {
		if err := opt(&applied); err != nil {
			t.Fatalf("apply option: %v", err)
		}
	}
	return applied
}

func writeTestFile(t *testing.T, name, body string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), name)
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	return path
}

// Test-only creds (a throwaway account generated by nsc, matching no environment).
const testCreds = `-----BEGIN NATS USER JWT-----
eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJURVNUIiwiaWF0IjoxLCJpc3MiOiJBVEVTVCIsIm5hbWUiOiJ0ZXN0Iiwic3ViIjoiVVRFU1QiLCJuYXRzIjp7InB1YiI6e30sInN1YiI6e30sInN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsInR5cGUiOiJ1c2VyIiwidmVyc2lvbiI6Mn19.c2ln
------END NATS USER JWT------

************************* IMPORTANT *************************
NKEY Seed printed below can be used to sign and prove identity.
NKEYs are sensitive and should be treated as secrets.

-----BEGIN USER NKEY SEED-----
SUAGKSV4OGPS3VCFLJ5V2R6ZVRA3NAOP6WQGKKTAYJWSSRSHCWZ2QVBBBI
------END USER NKEY SEED------

*************************************************************
`

// testCAPEM generates a throwaway self-signed certificate that stands in for the NATS server certificate file.
func testCAPEM(t *testing.T) string {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	template := &x509.Certificate{
		SerialNumber: big.NewInt(1), Subject: pkix.Name{CommonName: "nats-test"},
		NotBefore: time.Now().Add(-time.Hour), NotAfter: time.Now().Add(time.Hour),
		IsCA: true, BasicConstraintsValid: true, KeyUsage: x509.KeyUsageCertSign,
	}
	der, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		t.Fatal(err)
	}
	return string(pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der}))
}

func TestNATSOptionsUseCredsFileAndTLS(t *testing.T) {
	creds := writeTestFile(t, "nexus.creds", testCreds)
	ca := writeTestFile(t, "ca.pem", testCAPEM(t))
	applied := applyOptions(t, config.NATSConfig{
		Servers: []string{"tls://nats.example:4222"}, CredsFile: creds, CAFile: ca,
	})
	if applied.UserJWT == nil || applied.SignatureCB == nil {
		t.Fatal("creds_file must install the user JWT and nkey signature callbacks")
	}
	if applied.User != "" || applied.Password != "" {
		t.Fatalf("no user/password expected with creds, got %q", applied.User)
	}
	if !applied.Secure && applied.TLSConfig == nil {
		t.Fatal("tls:// with ca_file must produce a TLS configuration")
	}
}

func TestNATSOptionsTLSWithoutCAFileUsesSystemRoots(t *testing.T) {
	applied := applyOptions(t, config.NATSConfig{Servers: []string{"tls://nats.example:4222"}})
	if !applied.Secure {
		t.Fatal("tls:// without ca_file must still require TLS (system roots)")
	}
}

func TestNATSOptionsKeepUserPasswordForDev(t *testing.T) {
	applied := applyOptions(t, config.NATSConfig{Servers: []string{"nats://127.0.0.1:4222"}, User: "app", Password: "pw"})
	if applied.User != "app" || applied.Password != "pw" || applied.Secure || applied.UserJWT != nil {
		t.Fatalf("dev user/password options changed: %+v", applied)
	}
}

func TestNATSOptionsRejectUnreadableCreds(t *testing.T) {
	_, err := natsConnectOptions(config.NATSConfig{Servers: []string{"tls://n:4222"}, CredsFile: "/nonexistent/nexus.creds"})
	if err == nil || !strings.Contains(err.Error(), "creds_file") {
		t.Fatalf("missing creds file = %v, want an error naming creds_file", err)
	}
}
